#ifndef PROGRAMMING3_ASSIGNMENT5_EXERCISE_5_1_MAIN_H
#define PROGRAMMING3_ASSIGNMENT5_EXERCISE_5_1_MAIN_H

#include <ostream>
#include "Bibliography.h"

#endif //PROGRAMMING3_ASSIGNMENT5_EXERCISE_5_1_MAIN_H
